### ISSUE TITLE
'Invalid format string' - local time error

### ISSUE THREAD

**Issue by ahmadfantastic** [liffiton/Gen-Ed#5]
After running the codehelp app using `flask --app codehelp run` and submitting a help, it shows an internal server error. 

The server logs show: 
![image](https://github.com/user-attachments/assets/128e147f-1f3d-4cd6-ba64-f766c93da638)
 
After chnaging line 43 in tz.py from full date and time `return local_dt.strftime("%Y-%m-%d %-I:%M%P")` to only date `return local_dt.strftime("%Y-%m-%d")`, then everything seems to work fine.

**Comment by liffiton** [comment]
Thanks for the report!  It looks like it was an incompatibility between Windows and Linux/unix in the format specifier for a non-zero-padded hour (`%#I` vs `%-I`).  The commit I just pushed should fix it.

I don't test in Windows, myself, though, so please do report any other issues you encounter there.  Thanks!

**Comment by ahmadfantastic** [comment]
@liffiton The issues persist as seen below:
![image](https://github.com/user-attachments/assets/5079d26d-94d4-4025-bab8-b1ab03846d39)

**Comment by liffiton** [comment]
Ah, sorry.  Not testing on Windows makes this difficult.  Possibly the `%P` is also not supported on Windows.  If you have a chance to change both instances of `%P` to lowercase `%p` and let me know if that fixes it, that would be helpful.  I'll work on testing it on a Windows machine myself to check that, in any case.

**Comment by ahmadfantastic** [comment]
@liffiton Changing  `%P` to lowercase `%p` solves the issue. Just tried it and it worked!

**Comment by liffiton** [comment]
Awesome.  Thanks!  I'll work on testing on Windows going forward, too.
